version: '3.9'
services:
  db:
    image: postgres:14.5
    restart: always
    container_name: insurechain-db
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  db-test:
    image: postgres:14.5
    restart: always
    container_name: insurechain-db-tests
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - db-test:/var/lib/postgresql/data
volumes:
  db:
  db-test:
