version: '3.9'
services:
  db:
    image: postgres:14.5
    restart: always
    container_name: insurechain-db
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=dev
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db:
