### Basic Get
GET  http://localhost:3333/api/hello
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im90cm9AZ21haWwuY29tIiwic3ViIjoxLCJpYXQiOjE2NjE3NzcyNTMsImV4cCI6MTY2MTg2MzY1M30.F76P-C7ZLTBsl00CujLfEYcn9PSf5p9GPmhCOPm1Sds


###Create User
POST  http://localhost:3333/api/auth/signup
Content-Type: application/json

{
  "email": "pruvebasalt@gmail.com",
  "password": "1234abcd",
  "name": "pepito"
}

### Find user
GET http://localhost:3333/api/auth/1

### Sign in user
POST  http://localhost:3333/api/auth/signin
Content-Type: application/json

{
  "email": "pruebasalt@gmail.com",
  "password": "1234abcd"
}

### signin
POST  http://localhost:3333/api/auth/signin
Content-Type: application/json

{
  "email": "otro@gmail.com",
  "password": "1234"
}


### Get profile with Jwt
GET  http://localhost:3333/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBydWViYXNhbHRAZ21haWwuY29tIiwic3ViIjo0LCJpYXQiOjE2NjI2NjAyMjksImV4cCI6MTY2Mjc0NjYyOX0.3PMyyKkKA5i097HiU1_wcEQbIEdWyRhcflgbT1JK2rw
